apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: trusted-artifact-signer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: trusted-artifact-signer
    app.kubernetes.io/part-of: sigstore-ocp
  name: trusted-artifact-signer
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: trusted-artifact-signer
status:
  loadBalancer: {}
